version: '3'
services:
  openvpn:
    build: openvpn/
    env_file:
      - '.env'
    restart: always
    privileged: true
    ports:
     - "${OVPN_PORT}:1194/udp"
    networks:
      - vpn
    volumes:
      - vpnset:/etc/vpn-set/

  nginx:
    build: nginx/
    env_file:
      - '../vpn.env'
    restart: always
    privileged: false
    ports:
     - "${OVPN_PORT}:1194/tcp"
     - "${HTTP_PORT}:80/tcp"
    networks:
      - vpn
    volumes:
      - vpnset:/etc/vpn-set/

  ocserv:
    build: ocserv/
    env_file:
      - '../vpn.env'
    restart: always
    privileged: true
    ports:
     - "${OCSERV_PORT}:443/tcp"
     - "${OCSERV_PORT}:443/udp"
    networks:
      - vpn
    volumes:
      - vpnset:/etc/vpn-set/

  ovpnmon:
    image: ruimarinho/openvpn-monitor
    env_file:
      - '../vpn.env'
    restart: always
    privileged: false
    networks:
      - vpn


networks:
  vpn:
volumes:
  vpnset: