version: '3'
services:
  openvpn:
    container_name: vpnset-openvpn
    build: openvpn/
    image: "vpnset-openvpn:v0.3"
    env_file: .env
    restart: always
    privileged: true
    ports:
     - "${OVPN_PORT}:1194/udp"
    networks:
      - vpn
    volumes:
      - ./vpn-data/:/etc/vpnset

  nginx:
    container_name: nginx
    build: nginx/
    image: vpnset-nginx
    env_file: .env
    restart: always
    privileged: false
    ports:
     - "${OVPN_PORT}:1194/tcp"
     - "${HTTP_PORT}:443/tcp"
    networks:
      - vpn
    volumes:
      - ./vpn-data/:/etc/vpnset

  ocserv:
    container_name: ocserv
    build: ocserv/
    image: vpnset-ocserv
    env_file: .env
    restart: always
    privileged: true
    ports:
     - "${OCSERV_PORT}:443/tcp"
     - "${OCSERV_PORT}:443/udp"
    networks:
      - vpn
    volumes:
      - ./vpn-data/:/etc/vpnset

  ovpnmon:
    container_name: ovpnmon
    image: ruimarinho/openvpn-monitor
    env_file: .env
    restart: always
    privileged: false
    networks:
      - vpn


networks:
  vpn: